let flag = document.getElementById("flag");
let url = "https://raw.githubusercontent.com/oxguy3/flags/master/svg/"; // /be.svg
const europe = {
  AL: ["Albanië", "Tirana"],
  AD: ["Andorra", "Andorra la Vella"],
  AT: ["Oostenrijk", "Wenen"],
  AM: ["Armenië", "Yerevan"],
  AZ: ["Azerbeidjan", "Bakoe"],
  BA: ["Bosnië en Herzegovina", "Sarajevo"],
  BE: ["België", "Brussel"],
  BG: ["Bulgarije", "Sofia"],
  BY: ["Wit-Rusland", "Minsk"],
  CH: ["Zwitserland", "Bern"],
  CY: ["Cyprus", "Nicosia"],
  CZ: ["Tsjechië", "Praag"],
  DK: ["Denemarken", "Kopenhagen"],
  EE: ["Estland", "Talinn"],
  FI: ["Finland", "Helsinki"],
  FR: ["Frankrijk", "Parijs"],
  DE: ["Duitsland", "Berlijn"],
  GE: ["Georgië", "Tbilisi"],
  GR: ["Griekenland", "Athene"],
  HU: ["Hongarije", "Budapest"],
  HR: ["Kroatië", "Zagreb"],
  IE: ["Ierland", "Dublin"],
  IS: ["Ijsland", "Reykyavik"],
  IT: ["Italië", "Rome"],
  KZ: ["Kazachstan", "Nur-Sultan"],
  LI: ["Liechtenstein", "Vaduz"],
  LV: ["Letland", "Riga"],
  LT: ["Litouwen", "Vilnius"],
  LU: ["Luxemburg", "Luxemburg"],
  MD: ["Moldavië", "Chisinau"],
  ME: ["Montenegro", "Podgorica"],
  MC: ["Monaco", "Monaco Stad"],
  MT: ["Malta", "Valetta"],
  MK: ["Macedonië", "Skopje"],
  NL: ["Nederland", "Amsterdam"],
  NO: ["Noorwegen", "Oslo"],
  PL: ["Polen", "Warschau"],
  PT: ["Portugal", "Lissabon"],
  RO: ["Roemenië", "Boekarest"],
  RS: ["Servië", "Belgrado"],
  RU: ["Rusland", "Moskou"],
  SK: ["Slowakije", "Bratislava"],
  SI: ["Slovenië", "Ljubljana"],
  ES: ["Spanje", "Madrid"],
  SE: ["Zweden", "Stockholm"],
  SM: ["San Marino", "San Marino"],
  TR: ["Turkije", "Ankara"],
  VA: ["Vaticaan stad", "Vaticaan stad"],
  UA: ["Oekraïne", "Kiev"],
  GB: ["Groot-Britannië", "Londen"],
  XK: ["Kosovo", "Pristina"]
};

const countries = {
  AF: "Afghanistan",
  AX: "Aland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, Democratic Republic",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island & Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle Of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KR: "Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States Of",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  BL: "Saint Barthelemy",
  SH: "Saint Helena",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre And Miquelon",
  VC: "Saint Vincent And Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia And Sandwich Isl.",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard And Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis And Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe"
};

setInterval(pick, 567);


var randomProperty = function (obj) {
  var keys = Object.keys(obj);
  var rand = Math.round(keys.length * Math.random());
  console.log(rand);
  var res = obj[keys[rand << 0]];

  return [Object.keys(obj)[rand], res];
  //return obj[keys[(keys.length * Math.random()) << 0]];
};

function pick() {
  console.log("pick click");
  // var chosen = url + randomProperty(europe)[0].toLowerCase() + ".svg";
  var chosen = randomProperty(countries);
  console.log(chosen);
  flag.alt = chosen[0] + " - " + chosen[1];
  flag.src = url + chosen[0].toLowerCase() + ".svg";
  document.getElementById("country").innerHTML = flag.alt;
}

document.getElementById("pick").addEventListener("", () => {
  console.log("");
  pick();
});

document.onkeydown = checkKey;

function checkKey(e) {
  e = e || window.event;
  if (e.keyCode == "38") {
    pick();
  } else if (e.keyCode == "40") {
    // down arrow
  } else if (e.keyCode == "37") {
    // left arrow
  } else if (e.keyCode == "39") {
    pick(); // right arrow
  } else if (e.keyCode == "32") {
    pick(); // space bar
  }
}

